export interface IndianLanguage {
  code: string;
  name: string;
  nativeName: string;
  script: string;
  family: string;
  ttsVoice?: string;
}

export const INDIAN_LANGUAGES: IndianLanguage[] = [
  {
    code: 'en',
    name: 'English',
    nativeName: 'English',
    script: 'Latin',
    family: 'Indo-European',
    ttsVoice: 'en-IN-NeerjaNeural',
  },
  {
    code: 'auto',
    name: 'Auto Detect',
    nativeName: 'स्वतः पहचान / Auto',
    script: 'Multilingual',
    family: 'All',
  },
  {
    code: 'hi',
    name: 'Hindi',
    nativeName: 'हिन्दी',
    script: 'Devanagari',
    family: 'Indo-Aryan',
    ttsVoice: 'hi-IN-SwaraNeural',
  },
  {
    code: 'bn',
    name: 'Bengali',
    nativeName: 'বাংলা',
    script: 'Bengali',
    family: 'Indo-Aryan',
    ttsVoice: 'bn-IN-TanishaaNeural',
  },
  {
    code: 'te',
    name: 'Telugu',
    nativeName: 'తెలుగు',
    script: 'Telugu',
    family: 'Dravidian',
    ttsVoice: 'te-IN-ShrutiNeural',
  },
  {
    code: 'mr',
    name: 'Marathi',
    nativeName: 'मराठी',
    script: 'Devanagari',
    family: 'Indo-Aryan',
    ttsVoice: 'mr-IN-AarohiNeural',
  },
  {
    code: 'ta',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    script: 'Tamil',
    family: 'Dravidian',
    ttsVoice: 'ta-IN-PallaviNeural',
  },
  {
    code: 'ur',
    name: 'Urdu',
    nativeName: 'اردو',
    script: 'Perso-Arabic',
    family: 'Indo-Aryan',
    ttsVoice: 'ur-IN-GulNeural',
  },
  {
    code: 'gu',
    name: 'Gujarati',
    nativeName: 'ગુજરાતી',
    script: 'Gujarati',
    family: 'Indo-Aryan',
    ttsVoice: 'gu-IN-DhwaniNeural',
  },
  {
    code: 'kn',
    name: 'Kannada',
    nativeName: 'ಕನ್ನಡ',
    script: 'Kannada',
    family: 'Dravidian',
    ttsVoice: 'kn-IN-SapnaNeural',
  },
  {
    code: 'ml',
    name: 'Malayalam',
    nativeName: 'മലയാളം',
    script: 'Malayalam',
    family: 'Dravidian',
    ttsVoice: 'ml-IN-SobhanaNeural',
  },
  {
    code: 'or',
    name: 'Odia',
    nativeName: 'ଓଡ଼ିଆ',
    script: 'Odia',
    family: 'Indo-Aryan',
    ttsVoice: 'hi-IN-SwaraNeural',
  },
  {
    code: 'pa',
    name: 'Punjabi',
    nativeName: 'ਪੰਜਾਬੀ',
    script: 'Gurmukhi',
    family: 'Indo-Aryan',
    ttsVoice: 'hi-IN-SwaraNeural',
  },
  {
    code: 'as',
    name: 'Assamese',
    nativeName: 'অসমীয়া',
    script: 'Bengali-Assamese',
    family: 'Indo-Aryan',
    ttsVoice: 'bn-IN-TanishaaNeural',
  },
  {
    code: 'mai',
    name: 'Maithili',
    nativeName: 'मैथिली',
    script: 'Devanagari',
    family: 'Indo-Aryan',
    ttsVoice: 'hi-IN-SwaraNeural',
  },
  {
    code: 'sa',
    name: 'Sanskrit',
    nativeName: 'संस्कृतम्',
    script: 'Devanagari',
    family: 'Indo-Aryan',
    ttsVoice: 'hi-IN-SwaraNeural',
  },
  {
    code: 'sat',
    name: 'Santali',
    nativeName: 'ᱥᱟᱱᱛᱟᱲᱤ',
    script: 'Ol Chiki',
    family: 'Austroasiatic',
  },
  {
    code: 'ks',
    name: 'Kashmiri',
    nativeName: 'کٲشُر / कॉशुर',
    script: 'Perso-Arabic / Devanagari',
    family: 'Dardic',
    ttsVoice: 'ur-IN-GulNeural',
  },
  {
    code: 'ne',
    name: 'Nepali',
    nativeName: 'नेपाली',
    script: 'Devanagari',
    family: 'Indo-Aryan',
    ttsVoice: 'ne-NP-HemkalaNeural',
  },
  {
    code: 'kok',
    name: 'Konkani',
    nativeName: 'कोंकणी',
    script: 'Devanagari',
    family: 'Indo-Aryan',
    ttsVoice: 'mr-IN-AarohiNeural',
  },
  {
    code: 'sd',
    name: 'Sindhi',
    nativeName: 'سنڌي / सिन्धी',
    script: 'Perso-Arabic / Devanagari',
    family: 'Indo-Aryan',
    ttsVoice: 'ur-IN-GulNeural',
  },
  {
    code: 'doi',
    name: 'Dogri',
    nativeName: 'डोगरी',
    script: 'Devanagari',
    family: 'Indo-Aryan',
    ttsVoice: 'hi-IN-SwaraNeural',
  },
  {
    code: 'mni',
    name: 'Manipuri (Meitei)',
    nativeName: 'মৈতৈলোন্',
    script: 'Meetei Mayek / Bengali',
    family: 'Tibeto-Burman',
    ttsVoice: 'bn-IN-TanishaaNeural',
  },
  {
    code: 'brx',
    name: 'Bodo',
    nativeName: 'बड़ो',
    script: 'Devanagari',
    family: 'Tibeto-Burman',
    ttsVoice: 'hi-IN-SwaraNeural',
  },
  {
    code: 'bho',
    name: 'Bhojpuri',
    nativeName: 'भोजपुरी',
    script: 'Devanagari',
    family: 'Indo-Aryan',
    ttsVoice: 'hi-IN-SwaraNeural',
  },
  {
    code: 'en-IN',
    name: 'Indian English',
    nativeName: 'English (India)',
    script: 'Latin',
    family: 'Indo-European',
    ttsVoice: 'en-IN-NeerjaNeural',
  },
];

export const INDIAN_LANGUAGE_MAP: Record<string, IndianLanguage> = Object.fromEntries(
  INDIAN_LANGUAGES.map((l) => [l.code, l])
);
